CREATE DATABASE IF NOT EXISTS `scrum_poker`;

CREATE TABLE IF NOT EXISTS scrum_poker.users (
    id VARCHAR(255) PRIMARY KEY,
    room_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scrum_poker.rooms (
    id VARCHAR(255) PRIMARY KEY,
    turn INT(10) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scrum_poker.votes (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    room_id VARCHAR(255) NOT NULL,
    turn INT(10) NOT NULL DEFAULT 1,
    vote INT(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE USER 'mihai' IDENTIFIED BY 'pass';
GRANT ALL privileges ON `scrum_poker`.* TO 'mihai'@'%' IDENTIFIED BY 'pass';

CREATE USER 'read' IDENTIFIED BY 'read';
GRANT SELECT ON *.* TO 'read'@'%' IDENTIFIED BY 'read';